name: potato_market
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  provider:
  multi_image_picker:
  modal_progress_hud:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true